name: news_app
description: A complete Flutter news app with real API integration

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # HTTP requests
  http: ^1.1.0
  
  # Shared Preferences for theme and onboarding
  shared_preferences: ^2.2.2
  
  # Loading and error handling
  shimmer: ^3.0.0
  
  # Image caching
  cached_network_image: ^3.3.0
  
  # URL launcher for opening articles
  url_launcher: ^6.2.1
  
  # Date formatting
  intl: ^0.18.1
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true